-- MySQL Script generated by MySQL Workbench
-- 11/13/15 12:06:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wom` DEFAULT CHARACTER SET latin1 ;
USE `wom` ;

-- -----------------------------------------------------
-- Table `wom`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`user` (
  `account_number` INT(11) NOT NULL COMMENT '',
  `user_name` VARCHAR(45) NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`account_number`)  COMMENT '',
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`user_data` (
  `char_name` VARCHAR(45) NOT NULL COMMENT '',
  `char_level` INT(11) NOT NULL COMMENT '',
  `location_x` INT(11) NOT NULL COMMENT '',
  `location_y` INT(11) NOT NULL COMMENT '',
  `account_number` INT(11) NOT NULL COMMENT '',
  INDEX `account_number_idx` (`account_number` ASC)  COMMENT '',
  PRIMARY KEY (`account_number`, `char_name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`guild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`guild` (
  `guild_title` VARCHAR(35) NOT NULL COMMENT '',
  `char_name` VARCHAR(45) NOT NULL COMMENT '',
  `leaderflag` TINYINT(1) NOT NULL COMMENT '',
  UNIQUE INDEX `guild_title` (`guild_title` ASC)  COMMENT '',
  PRIMARY KEY (`guild_title`, `char_name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`purchase_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`purchase_table` (
  `account_number` INT(11) NOT NULL COMMENT '',
  `card_number` INT(11) NOT NULL COMMENT '',
  `card_type` VARCHAR(35) NOT NULL COMMENT '',
  `transaction_amt` INT(11) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`account_number`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`quests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`quests` (
  `quest_title` VARCHAR(125) NOT NULL COMMENT '',
  `completion` INT(11) NOT NULL COMMENT '',
  `quest_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`quest_id`)  COMMENT '',
  UNIQUE INDEX `quest_id_UNIQUE` (`quest_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`user_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`user_friends` (
  `account_number` INT(11) NOT NULL COMMENT '',
  `friend_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`account_number`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `wom`.`user_quests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wom`.`user_quests` (
  `char_name` VARCHAR(45) NOT NULL COMMENT '',
  `quest_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`char_name`, `quest_id`)  COMMENT '',
  INDEX `quest_id_idx` (`quest_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
